### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cashburner** [Ajatt-Tools/mortician#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-28 20:05:38

Caught exception:
Traceback (most recent call last):
  File "aqt\reviewer.py", line 298, in <lambda>
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-52>", line 2, in _answerCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 633, in repl
  File "aqt\reviewer.py", line 265, in _answerCard
  File "anki\schedv2.py", line 85, in answerCard
AssertionError

**Comment by tatsumoto-ren** [comment]
Could you please tell how the error happened? Did it occur just before or after a card should have got buried?

**Comment by Cashburner** [comment]
when the card was supposed to get buried, f.e. after 5 reviews it popped the notification that it got buried BUT the card reappeared again in the reviews (not sure if right next or after a couple of cards) but this time couldn't rate it again or good at all and it gave this error. (Gave error, and couldn't move to next card)

**Comment by tatsumoto-ren** [comment]
I can't reproduce the bug on my machine. Did the add-on work before? Do you remember when it stopped working? Does it work if you disable other add-ons?

**Comment by Cashburner** [comment]
{
    "again_notify": false,
    "again_threshold": 4,
    "count_from_daystart": true,
    "tag_on_bury": "",
    "timeframe": 24
}

these are the settings I used. Not sure about that, I don't have time to do testing probably later

**Comment by tatsumoto-ren** [comment]
Good, I'm going to do additional testing with your settings and see if something changes.

**Comment by tatsumoto-ren** [comment]
I couldn't find any errors.

**Comment by Cashburner** [comment]
![Screenshot_514](https://user-images.githubusercontent.com/1826311/106367266-fe96f300-6349-11eb-9409-a48e44dfd504.png)
Check out and my list of addons. I know they are a lot but probably one of them does the problem. Keep in mind that I exclude dakillzone when I used the addon. any ideas?

**Comment by Cashburner** [comment]
also something interesting is that when the card gets buried it keeps being in the next review queues and gives error but when I go back to decks, the correct queue no is displayed and also when I check the browser I see the card as buried and also if I go back to reviewing that deck it everything is fine. I think for some reason the card gets buried successfully but does not get removed from the following review queue, not sure why. Keep in mind that I use the v2 scheduler, not sure if this is what causes the prob. Will look into it further since I like the addon

**Comment by tatsumoto-ren** [comment]
According to your first post, the crash happens in `schedv2.py` on line 85:
```
        assert 0 <= card.queue <= 4
```
Apparently it tries to answer a buried card, that's why the assertion fails.
Another add-on might be involved, since you have many of them.

**Comment by Cashburner** [comment]
so I disabled all addons and tried only with mortician. same thing happened, don't know why. Keep in mind that if I bury the card manually then it gets buried fine (meaning it gets removed from the review queue), also another addon which does the same thing but only with review cards buried the cards successfully. I prefer mortician but I don't know why I keep getting the error. What else could be the problem? In what anki version you test it?

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-30 21:09:28

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\reviewer.py", line 329, in _onAnswerButton
  File "aqt\reviewer.py", line 265, in _answerCard
  File "anki\schedv2.py", line 85, in answerCard
AssertionError

**Comment by tatsumoto-ren** [comment]
I've been testing on
```
Version 2.1.35 (84dcaa86)
Python 3.9.1 Qt 5.15.2 PyQt 5.15.2
Platform: Arch Linux
```
I'll try it with your version then.

**Comment by tatsumoto-ren** [comment]
I was able to get the same error on a windows machine. I think it is windows-specific.

**Comment by Cashburner** [comment]
thanks for the help, can you specify more about the error? curious

**Comment by tatsumoto-ren** [comment]
Apparently it was needed to explicitly reset the learning queue. I added the corresponding call in 8bec7ce188c085034cc43527c04f15535fda36a4.

**Comment by Cashburner** [comment]
Thanks a lot for everything. It got fixed. And thanks for the amazing addon. Keep up the great work!
