### ISSUE TITLE
REQUEST: Notification Optional

### ISSUE THREAD

**Issue by Cashburner** [Ajatt-Tools/mortician#3]
Hello, quick suggestion/request. Great addon btw: 

Add a simple option to hide the "buried because taped again 5 times" notification. 

I find myself sometimes losing the pace when I answer fast reviews and it pops up sometimes. It is good that it is there so you know the addon is working, but an option to make the notification optional would help a lot.

Thanks a lot! Keep up the great work!!!!

**Comment by tatsumoto-ren** [comment]
I think you can disable the tooltips if you set `disable_tooltips` to `true` in the config.
