### ISSUE TITLE
QUERY: Mark rather than bury.

### ISSUE THREAD

**Issue by huandney** [Ajatt-Tools/mortician#4]
I wanted to know if, instead of burying, this addon could mark a red flag card for example.
thank you!

**Comment by tatsumoto-ren** [comment]
It's totally possible, I'll work on it.

**Comment by tatsumoto-ren** [comment]
I've added two more config options:
* `flag` - specify what flag to use. `Red`, `Orange`, `Green`, `Blue` or none. 
* `no_bury` - disable burying completely.

If you enable both, you should get what you need.

**Comment by huandney** [comment]
Thank you very much!
