### ISSUE TITLE
feature request; setting for ignoring learning cards

### ISSUE THREAD

**Issue by CappieXL** [Ajatt-Tools/mortician#5]
This addon is amazig, together with auto ease factor it makes Anki even more powerful than it already is!

Would it be possible to add a setting which disables burying only for learning cards? I do my new cards after everything else, so when I do new cards I almost always have time and energy to spare. I would love if this addon would ignore cards that haven't graduated yet. Right now I disable the addon if I decide to do new cards so I can try to memorize new information without pressure. However, that also stops the auto-burying for lapsed cards which are still waiting in the queue for their next review, for which I would ultimately like to keep the addon enabled.

**Comment by tatsumoto-ren** [comment]
I don't think it's a good idea, but it can be added.
For example, what if you keep forgetting a new card?

**Comment by CappieXL** [comment]
Well cards would need to graduate before the addon kicks in. So new cards would just not get auto burried. 

I do not see why that would be bad?

**Comment by tatsumoto-ren** [comment]
I think it would be bad if you try to learn a new card but it doesn't stick so it can't graduate.
