### ISSUE TITLE
QUERY: About the operation and suggestion.

### ISSUE THREAD

**Issue by huandney** [Ajatt-Tools/mortician#8]
Hi,
Does this addon change the "Leech threshold" of the "Deck Options"? For example, I have decks that I set the "Leech threshold" to 3 errors and others to 5, that is, if I have the addon activated it will ignore the individual settings of each deck?

If so, I would suggest being able to have an option to let each individual deck control the "Leech threshold".

Another question I don't understand very well, what is the "timeframe" for?

Thanks!

**Comment by tatsumoto-ren** [comment]
> Does this addon change the "Leech threshold" of the "Deck Options"?

No, the add-on has its own settings. They act independently from each deck's options.

> let each individual deck control the "Leech threshold".

This add-on doesn't prevent you from controlling the leech threshold of individual decks.
However, the bury threshold is currently a global setting.
If you suggest that the setting should be controlled on a per-deck basis, this could be added in the future.

> what is the "timeframe" for?

If you hover over the spinbox, it gives you a tooltip explaining what it does.

**Comment by huandney** [comment]
> If you suggest that the setting should be controlled on a per-deck basis, this could be added in the future.

it would be something interesting.

thanks!
